apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langfuse-clickhouse-logs-pvc
  namespace: multi-agents
  labels:
    app.kubernetes.io/name: langfuse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
