apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-config
  namespace: multi-agents
  labels:
    app.kubernetes.io/name: langfuse
data:
  TELEMETRY_ENABLED: "false"
  LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "true"
  CLICKHOUSE_CLUSTER_ENABLED: "false"
  LANGFUSE_S3_EVENT_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_EVENT_UPLOAD_REGION: "auto"
  LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "minio"
  LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_EVENT_UPLOAD_PREFIX: "events/"
  LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: "langfuse"
  LANGFUSE_S3_MEDIA_UPLOAD_REGION: "auto"
  LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "minio"
  LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
  LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: "media/"
  LANGFUSE_S3_BATCH_EXPORT_ENABLED: "false"
  REDIS_PORT: "6379"
  REDIS_TLS_ENABLED: "false"
  NEXTAUTH_URL: "http://localhost:3000"
  LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "miniosecret"
  LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "miniosecret"
