apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: multi-agents
type: Opaque
stringData:
  POSTGRES_USER: hoteluser
  POSTGRES_PASSWORD: hotelpass
  POSTGRES_DB: hotelsdb
  DATABASE_URL: postgresql+psycopg://hoteluser:hotelpass@pgbouncer-svc.multi-agents.svc.cluster.local:5432/hotelsdb
  userlist.txt: '"hoteluser" "hotelpass"'
